### ISSUE TITLE
Length of cortex_out?

### ISSUE THREAD

**Issue by BceClerget** [Rocsg/Macros_ImageJ_AgroBio#12]
I reached the conclusion that the cross-cuts with convex shapes results from large collapse caused by the large lacunae. However, it seems that the exodermis keeps its original length. Would it feasible to estimate the length (in pixels) of the exodermis in order to get an other estimate of the cortex area (supposed circular) before the collapse?

**Comment by BceClerget** [comment]
![50_i_3_b_externe](https://github.com/Rocsg/Macros_ImageJ_AgroBio/assets/137392328/e94d0a09-8ee4-4f67-a233-e832b0ec4424)
I forgot the example.

**Comment by Rocsg** [comment]
I see your point. However, care on something : from a perimeter, the radius can vary in some proportion based on the amount of ellipsisness.

**Comment by BceClerget** [comment]
Sure, but there is no better way. If feasible (?) it will give an additional area to the cortex, 100% occupied by lacunae. Thus the error will be partially minimized in the ratio. I hope it could be a solution to my current dilemma  with the variety sorting when grown in the subtrate.

**Comment by Rocsg** [comment]
Solved. It generates a perimeter.csv

**Comment by BceClerget** [comment]
Thank you. It does not produce a result in my computer. Do I need an additional macro?
