### ISSUE TITLE
Missing tifendoderm

### ISSUE THREAD

**Issue by BceClerget** [Rocsg/Macros_ImageJ_AgroBio#8]
I fixed a trouble with a call to tifendoderm (probably useless) in step5 by changing to comment lines 40 to 42. However I anticipate that the same trouble can be expected when using step9 to create the file of results that includes this information. Any possible patch, please ?

**Comment by BceClerget** [comment]
I wrongly anticipated: no trouble at all during step9 so this issue is solved

**Comment by Rocsg** [comment]
Solved.
